"use client";

import { useState, useEffect } from "react";

export default function ResponsesPage() {
  const [responses, setResponses] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchResponses = async () => {
    setLoading(true);
    const res = await fetch("/api/responses");
    const data = await res.json();
    setResponses(data || []);
    setLoading(false);
  };

  useEffect(() => {
    fetchResponses();
  }, []);

  const getModelColor = (modelName: string) => {
    if (modelName.includes("gpt")) return "bg-blue-500/20 text-blue-400 border-blue-500/30";
    if (modelName.includes("claude")) return "bg-orange-500/20 text-orange-400 border-orange-500/30";
    if (modelName.includes("gemini")) return "bg-purple-500/20 text-purple-400 border-purple-500/30";
    return "bg-slate-500/20 text-slate-400 border-slate-500/30";
  };

  return (
    <div className="p-8 max-w-6xl mx-auto space-y-8">
      <div className="flex justify-between items-start">
        <div>
          <h1 className="text-3xl font-bold bg-gradient-to-r from-blue-400 to-purple-500 bg-clip-text text-transparent mb-2">
            LLM Responses
          </h1>
          <p className="text-slate-400">
            View how different models responded to your tracked prompts.
          </p>
        </div>
        <button
          onClick={fetchResponses}
          className="bg-slate-800 hover:bg-slate-700 text-white px-4 py-2 rounded-lg font-medium transition-colors border border-slate-700"
        >
          ↻ Refresh
        </button>
      </div>

      <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden overflow-x-auto shadow-2xl">
        <table className="w-full text-left text-sm">
          <thead className="bg-slate-900/80 border-b border-slate-800 text-slate-400">
            <tr>
              <th className="p-4 font-medium">Date</th>
              <th className="p-4 font-medium min-w-[200px]">Prompt</th>
              <th className="p-4 font-medium">Model</th>
              <th className="p-4 font-medium w-1/2">Response</th>
              <th className="p-4 font-medium text-center">Data Type</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-800/50">
            {loading ? (
              <tr>
                <td colSpan={5} className="p-8 text-center text-slate-500">
                  Loading responses...
                </td>
              </tr>
            ) : responses.length === 0 ? (
              <tr>
                <td colSpan={5} className="p-8 text-center text-slate-500">
                  No responses recorded yet. Go to the Prompts tab to run the polling engine.
                </td>
              </tr>
            ) : (
              responses.map((r) => (
                <tr key={r.id} className="hover:bg-slate-800/20 transition-colors">
                  <td className="p-4 text-slate-500 whitespace-nowrap">
                    {new Date(r.createdAt).toLocaleString(undefined, {
                      month: "short",
                      day: "numeric",
                      hour: "numeric",
                      minute: "2-digit",
                    })}
                  </td>
                  <td className="p-4 text-slate-300">{r.prompt?.text || "Unknown Prompt"}</td>
                  <td className="p-4">
                    <span className={`px-2.5 py-1 rounded-md text-xs font-medium border ${getModelColor(r.modelName)}`}>
                      {r.modelName}
                    </span>
                  </td>
                  <td className="p-4 text-slate-300 leading-relaxed">
                    <div className="max-h-32 overflow-y-auto pr-2 custom-scrollbar">
                      {r.responseText}
                    </div>
                  </td>
                  <td className="p-4 text-center">
                    {r.isMock ? (
                      <span className="bg-yellow-500/10 text-yellow-500 text-xs px-2 py-1 rounded border border-yellow-500/20 cursor-help" title="Generated by Mock Mode">
                        MOCK
                      </span>
                    ) : (
                      <span className="bg-green-500/10 text-green-400 text-xs px-2 py-1 rounded border border-green-500/20">
                        LIVE
                      </span>
                    )}
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
